import Link from "next/link";
import Head from "next/head";

import './globals.css';

export default function RootLayout({
  children,
  title = "Create Next App",
  description = "Generated by create next app"
}: {
  children: React.ReactNode,
  title?: string,
  description?: string
}) {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content={description} />
        {/* If you want to include the Inter font the traditional way: */}
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap" rel="stylesheet" />
      </Head>

      <nav>
        <Link href="/">Home Page</Link>
        <Link href="/about">About</Link>
        <Link href="/pantry">Pantry</Link>
        <Link href="/recipetest">Recipe</Link>
      </nav>

      {children}
    </div>
  );
}
